In [1]:
import networkx
import pandas as pd
# pd.set_option('max_rows', 400)
import matplotlib.pyplot as plt

In [2]:
# 5.1 : Reading graph data from a CSV file

got_df = pd.read_csv('got-edges.csv')
got_df.head()

  Source   Target  Weight
0  Aemon    Grenn       5
1  Aemon  Samwell      31
2  Aerys    Jaime      18
3  Aerys   Robert       6
4  Aerys   Tyrion       5

In [19]:
# 5.2 Create graph

G = networkx.from_pandas_edgelist(got_df, 'Source', 'Target', 'Weight')
networkx.write_graphml(G, 'GOT-network.graphml')

plt.figure(figsize=(12,10))

# pos = networkx.kamada_kawai_layout(G)
# pos = networkx.spring_layout(G, seed=100)
pos = networkx.circular_layout(G)
# networkx.draw(G, with_labels=True, pos=pos, node_color='skyblue', width=.3, font_size=10)
# networkx.draw_networkx_edge_labels(G, pos=pos, edge_labels=networkx.get_edge_attributes(G, 'Weight'), font_color='red', font_size=7)

In [4]:
# 5.3 Stevilo povezav osebe / Who has the most number of connections in the network?
networkx.degree(G)

DegreeView({'Aemon': 5, 'Grenn': 4, 'Samwell': 15, 'Aerys': 4, 'Jaime': 24, 'Robert': 18, 'Tyrion': 36, 'Tywin': 22, 'Alliser': 3, 'Mance': 12, 'Amory': 1, 'Oberyn': 7, 'Arya': 19, 'Anguy': 2, 'Beric': 6, 'Bran': 14, 'Brynden': 8, 'Cersei': 20, 'Gendry': 4, 'Gregor': 12, 'Joffrey': 18, 'Jon': 26, 'Rickon': 6, 'Roose': 4, 'Sandor': 13, 'Thoros': 5, 'Balon': 6, 'Loras': 9, 'Belwas': 4, 'Barristan': 6, 'Illyrio': 1, 'Hodor': 4, 'Jojen': 4, 'Luwin': 2, 'Meera': 5, 'Nan': 2, 'Theon': 4, 'Brienne': 7, 'Bronn': 4, 'Podrick': 5, 'Lothar': 5, 'Walder': 8, 'Catelyn': 18, 'Edmure': 8, 'Hoster': 3, 'Jeyne': 2, 'Lysa': 10, 'Petyr': 7, 'Robb': 25, 'Roslin': 4, 'Sansa': 26, 'Stannis': 14, 'Elia': 5, 'Ilyn': 6, 'Meryn': 7, 'Pycelle': 4, 'Shae': 5, 'Varys': 7, 'Craster': 5, 'Karl': 1, 'Daario': 4, 'Drogo': 4, 'Irri': 4, 'Daenerys': 14, 'Aegon': 1, 'Jorah': 6, 'Kraznys': 1, 'Missandei': 2, 'Rakharo': 1, 'Rhaegar': 6, 'Viserys': 3, 'Worm': 1, 'Davos': 5, 'Cressen': 1, 'Salladhor': 1, 'Eddard': 12, 'Eddison': 3, 'Gilly': 4, 'Qyburn': 1, 'Renly': 8, 'Tommen': 5, 'Janos': 6, 'Bowen': 2, 'Kevan': 6, 'Margaery': 7, 'Myrcella': 4, 'Dalla': 3, 'Melisandre': 4, 'Orell': 1, 'Qhorin': 5, 'Rattleshirt': 4, 'Styr': 2, 'Val': 4, 'Ygritte': 4, 'Jon Arryn': 2, 'Lancel': 1, 'Olenna': 2, 'Marillion': 3, 'Robert Arryn': 3, 'Ellaria': 2, 'Mace': 3, 'Rickard': 2, 'Ramsay': 1, 'Chataya': 2, 'Shireen': 1, 'Doran': 1, 'Walton': 1})

In [5]:
degrees = dict(networkx.degree(G))
networkx.set_node_attributes(G, name='degree', values=degrees)

degree_df = pd.DataFrame(G.nodes(data='degree'), columns=['node', 'degree'])
#degree_df = degree_df.sort_values(by='degree', ascending=False)
degree_df

        node  degree
0      Aemon       5
1      Grenn       4
2    Samwell      15
3      Aerys       4
4      Jaime      24
..       ...     ...
102   Ramsay       1
103  Chataya       2
104  Shireen       1
105    Doran       1
106   Walton       1

[107 rows x 2 columns]

In [18]:
num_nodes = 20
df_sorted = degree_df.sort_values(by='degree', ascending=False)
#df_sorted.plot(x='node', y='degree', kind='barh').invert_yaxis()

In [13]:
# 5.6 Weighted degree - upošteva tudi težo povezav (število skupnih prizadevanj, skupnih dogodkov, ipd.)

networkx.degree(G, weight='Weight')

weighted_degrees = dict(networkx.degree(G, weight='Weight'))
networkx.set_node_attributes(G, name='weighted_degree', values=weighted_degrees)

degree_df['weighted_degree'] = degree_df['node'].map(weighted_degrees)

# Izrisi graf


networkx.write_graphml(G, 'GOT-network-02.graphml')

In [14]:
# 5.7
plt.figure(figsize=(10,9))

In [ ]:
# 5.8
# Who connects the most other nodes in the network?
# Betweenness centrality - meri, koliko krat je vozlišče na najkrajši poti med dvema drugima vozliščema. Višja vrednost pomeni, da vozlišče deluje kot pomemben posrednik ali "most" v omrežju.

betweenness_centrality = networkx.betweenness_centrality(G)
print(betweenness_centrality)

degree_df['betweenness'] = degree_df['node'].map(betweenness_centrality)

degree_df
# Izrisi graf (barh)

{'Aemon': 0.004622508177397137, 'Grenn': 5.989817310572027e-05, 'Samwell': 0.03227262859511145, 'Aerys': 0.0, 'Jaime': 0.09994344156136246, 'Robert': 0.2094523840293194, 'Tyrion': 0.19791284320277353, 'Tywin': 0.06553840423231058, 'Alliser': 0.0, 'Mance': 0.007275961371756524, 'Amory': 0.0, 'Oberyn': 0.01958014232946847, 'Arya': 0.07960711308183888, 'Anguy': 0.0, 'Beric': 0.0006091214266627511, 'Bran': 0.06301659941786954, 'Brynden': 0.004727134574764742, 'Cersei': 0.02674643287824232, 'Gendry': 0.0, 'Gregor': 0.005879915417737236, 'Joffrey': 0.025434099443917696, 'Jon': 0.22996466368473173, 'Rickon': 0.0007626320968639029, 'Roose': 0.0002629599012559427, 'Sandor': 0.014162278987154626, 'Thoros': 0.0019261823273239152, 'Balon': 0.0006281164805527878, 'Loras': 0.003780752291533962, 'Belwas': 0.018867924528301886, 'Barristan': 0.04011407489067884, 'Illyrio': 0.0, 'Hodor': 0.0021937273446681065, 'Jojen': 0.0004064518889316733, 'Luwin': 0.0, 'Meera': 0.0019922569692430686, 'Nan': 0.0, 'Theon': 0.00047177590304274953, 'Brienne': 0.0015376001520469229, 'Bronn': 0.00010482180293501046, 'Podrick': 0.0008358985235471674, 'Lothar': 0.0006600525898733143, 'Walder': 0.0032731813973401044, 'Catelyn': 0.04890588265764755, 'Edmure': 0.0063172332740347534, 'Hoster': 0.0002426336765959408, 'Jeyne': 0.0, 'Lysa': 0.015215156305177053, 'Petyr': 0.0011502139845250673, 'Robb': 0.1269644713830151, 'Roslin': 6.751960581039384e-05, 'Sansa': 0.12672031668498004, 'Stannis': 0.1026998617273264, 'Elia': 0.002996853410630337, 'Ilyn': 0.0, 'Meryn': 0.00025900705642512993, 'Pycelle': 0.0, 'Shae': 0.0012523948930099663, 'Varys': 0.0009094137867722772, 'Craster': 0.018867924528301886, 'Karl': 0.0, 'Daario': 5.989817310572027e-05, 'Drogo': 5.989817310572027e-05, 'Irri': 0.00017969451931716083, 'Daenerys': 0.15720345212054956, 'Aegon': 0.0, 'Jorah': 0.002329891127259132, 'Kraznys': 0.0, 'Missandei': 0.0, 'Rakharo': 0.0, 'Rhaegar': 0.007312671807481101, 'Viserys': 0.015644391307527945, 'Worm': 0.0, 'Davos': 0.056064690026954175, 'Cressen': 0.0, 'Salladhor': 0.0, 'Eddard': 0.019341416465723616, 'Eddison': 0.0, 'Gilly': 0.0, 'Qyburn': 0.0, 'Renly': 0.004227926858198188, 'Tommen': 0.0006984420191967362, 'Janos': 0.02355861153253357, 'Bowen': 0.0, 'Kevan': 0.019219915043818533, 'Margaery': 0.0010973522354777933, 'Myrcella': 0.0006235971795124951, 'Dalla': 0.0, 'Melisandre': 0.00860866854841803, 'Orell': 0.0, 'Qhorin': 0.0002635519616651692, 'Rattleshirt': 0.0, 'Styr': 0.0, 'Val': 0.005898334987101542, 'Ygritte': 0.0, 'Jon Arryn': 0.0005764583325230229, 'Lancel': 0.0, 'Olenna': 0.0, 'Marillion': 0.0, 'Robert Arryn': 0.0, 'Ellaria': 0.0, 'Mace': 0.0, 'Rickard': 0.0, 'Ramsay': 0.0, 'Chataya': 0.0, 'Shireen': 0.0, 'Doran': 0.0, 'Walton': 0.0}

        node  degree  weighted_degree  betweenness  community
0      Aemon       5               74     0.004623          1
1      Grenn       4               81     0.000060          1
2    Samwell      15              282     0.032273          1
3      Aerys       4               37     0.000000          0
4      Jaime      24              372     0.099943          0
..       ...     ...              ...          ...        ...
102   Ramsay       1                4     0.000000          2
103  Chataya       2                9     0.000000          0
104  Shireen       1                5     0.000000          1
105    Doran       1                5     0.000000          0
106   Walton       1               10     0.000000          0

[107 rows x 5 columns]

In [ ]:
# 5.9 Communities - skupnosti v omrežju
from networkx.algorithms import community

# Find communities in the graph using the greedy modularity maximization algorithm

communities = community.greedy_modularity_communities(G)   #weight='Weight')   #
communities

[frozenset({'Aerys',
            'Amory',
            'Balon',
            'Bronn',
            'Chataya',
            'Doran',
            'Elia',
            'Ellaria',
            'Gregor',
            'Ilyn',
            'Jaime',
            'Joffrey',
            'Kevan',
            'Lancel',
            'Loras',
            'Mace',
            'Margaery',
            'Meryn',
            'Myrcella',
            'Oberyn',
            'Olenna',
            'Podrick',
            'Pycelle',
            'Qyburn',
            'Renly',
            'Sandor',
            'Shae',
            'Tommen',
            'Tyrion',
            'Tywin',
            'Varys',
            'Walton'}),
 frozenset({'Aemon',
            'Alliser',
            'Bowen',
            'Craster',
            'Cressen',
            'Dalla',
            'Davos',
            'Eddison',
            'Gilly',
            'Grenn',
            'Hodor',
            'Janos',
            'Jojen',
            'Jon',
            'Karl',
            'Mance',
            'Meera',
            'Melisandre',
            'Orell',
            'Qhorin',
            'Rattleshirt',
            'Salladhor',
            'Samwell',
            'Shireen',
            'Stannis',
            'Styr',
            'Val',
            'Ygritte'}),
 frozenset({'Arya',
            'Bran',
            'Brienne',
            'Brynden',
            'Catelyn',
            'Cersei',
            'Eddard',
            'Edmure',
            'Hoster',
            'Jeyne',
            'Lothar',
            'Luwin',
            'Lysa',
            'Marillion',
            'Nan',
            'Petyr',
            'Ramsay',
            'Rickard',
            'Rickon',
            'Robb',
            'Robert Arryn',
            'Roose',
            'Roslin',
            'Sansa',
            'Theon',
            'Walder'}),
 frozenset({'Aegon',
            'Barristan',
            'Belwas',
            'Daario',
            'Daenerys',
            'Drogo',
            'Illyrio',
            'Irri',
            'Jon Arryn',
            'Jorah',
            'Kraznys',
            'Missandei',
            'Rakharo',
            'Rhaegar',
            'Robert',
            'Viserys',
            'Worm'}),
 frozenset({'Anguy', 'Beric', 'Gendry', 'Thoros'})]

In [16]:
# 5.10
# Make a dictionary by looping through the communities and, for each member of the community, adding their community number
community_dict = {}
for i, community in enumerate(communities):
    for member in community:
        community_dict[member] = i
        

degree_df['community'] = degree_df['node'].map(community_dict)
degree_df

        node  degree  weighted_degree  betweenness  community
0      Aemon       5               74     0.004623          1
1      Grenn       4               81     0.000060          1
2    Samwell      15              282     0.032273          1
3      Aerys       4               37     0.000000          0
4      Jaime      24              372     0.099943          0
..       ...     ...              ...          ...        ...
102   Ramsay       1                4     0.000000          2
103  Chataya       2                9     0.000000          0
104  Shireen       1                5     0.000000          1
105    Doran       1                5     0.000000          0
106   Walton       1               10     0.000000          0

[107 rows x 5 columns]

In [17]:
plt.figure(figsize=(10,9))